import IUser from "./model/user.model.interface"
import IOrder from "./model/order.model.interface"
import IProduct from "./model/products.model.interface"
import IReview from "./model/review.model.interface"
import IUserService from "./service/user.service.interface"
import IRoute from "./routes/route.interface"
import IProductService from "./service/product.service.interface"
import ICategory from "./model/category.model.interface"
import ICart from "./model/cart.model.interface"
import IAdmin from "./model/admin.model.interface"
import IAdminService from "./service/admin.service.interface"
export { IUser, IOrder, IProduct, IReview, IUserService, IRoute, IProductService, ICategory, ICart, IAdmin, IAdminService }